// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqxqteqznwlkmwjjlmlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeHF0ZXF6bndsa213ampsbWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzU2NDgsImV4cCI6MjA2MzkxMTY0OH0.bPP7-_mvELi33LWfMs5r80w_C40y0kk9uJmGq6yZ1bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);